spring.datasource.url=jdbc:h2:file:./data/silgis_db;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.messages.basename=messages
spring.messages.encoding=UTF-8

server.port=${PORT:8080}

spring.thymeleaf.cache=false





